#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use App\Commands\CalculateCommissions;
use App\Services\CommissionCalculator\CommissionCalculator;
use App\Services\CountryCodeProvider\CountryCodeProvider;
use App\Services\CurrencyRateProvider\CurrencyRateProvider;
use App\Services\TransactionsParser\TransactionsParser;
use GuzzleHttp\Client;
use Symfony\Component\Console\Application;

// ideally the apiKey should be retrieved from an env variable
$apiKey = '2q6zfYOPkT0xHY8YP0wQHPgCgxeaZMJQ';

$application = new Application();

$httpClient = new Client();

$application->add(
    new CalculateCommissions(
        new TransactionsParser(),
        new CommissionCalculator(new CountryCodeProvider($httpClient), new CurrencyRateProvider($httpClient, $apiKey))
    )
);

$application->run();
